
POST http://localhost:8082/admin/reset
###
GET http://localhost:8082/app/
###
GET http://localhost:8082/admin/metrics
###
GET http://localhost:8082/api/healthz
###
POST http://localhost:8082/api/chirps
content-type: application/json

{
    "body": "Hey there I am wanting to put your foot in my butt for sexual pleasure.",
    "user_id": "0a770795-2eb5-4bfa-b4d2-e172053f2345"
}
###
POST http://localhost:8082/api/chirps
content-type: application/json

{
    "body": "test",
    "user_id": "0a770795-2eb5-4bfa-b4d2-e172053f2345"
}
###
POST http://localhost:8082/api/users
content-type: application/json

{
    "email": "gleasoncr@gmail.com",
    "password": "password"
}

###
GET http://localhost:8082/api/chirps

###

GET http://localhost:8082/api/chirps/715d2e21-3718-47e5-afc9-317be54be347